const bookList =  [
    {
      "bookID": 1,
      "bookName": "The Great Gatsby",
      "author": "F. Scott Fitzgerald",
      "image": "src/assets/dating-book.png",
      "review": "A timeless classic depicting the glamour and decay of the American Dream.",
      "totalPages": 180,
      "rating": 4.5,
      "category": "Fiction",
      "tags": ["Classic", "Romance"],
      "publisher": "Scribner",
      "yearOfPublishing": 1925
    },
    {
      "bookID": 2,
      "bookName": "1984",
      "author": "George Orwell",
      "image": "src/assets/money-book.png",
      "review": "A chilling portrayal of a dystopian society where freedom is restricted and truth is manipulated.",
      "totalPages": 328,
      "rating": 4.8,
      "category": "Fiction",
      "tags": ["Dystopian", "Political"],
      "publisher": "Secker & Warburg",
      "yearOfPublishing": 1949
    },
    {
      "bookID": 3,
      "bookName": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "image": "src/assets/hate-book.png",
      "review": "A poignant narrative addressing racial injustice and moral growth in a small Southern town.",
      "totalPages": 281,
      "rating": 4.7,
      "category": "Fiction",
      "tags": ["Coming of Age", "Legal Drama"],
      "publisher": "J. B. Lippincott & Co.",
      "yearOfPublishing": 1960
    },
    {
      "bookID": 4,
      "bookName": "The Catcher in the Rye",
      "author": "J.D. Salinger",
      "image": "src/assets/monthly-book.png",
      "review": "An iconic portrayal of teenage angst and rebellion in a society perceived as phony.",
      "totalPages": 224,
      "rating": 4.3,
      "category": "Fiction",
      "tags": ["Young Adult", "Cultural"],
      "publisher": "Little, Brown and Company",
      "yearOfPublishing": 1951
    },
    {
      "bookID": 5,
      "bookName": "Pride and Prejudice",
      "author": "Jane Austen",
      "image": "src/assets/taxas-book.png",
      "review": "A witty and romantic exploration of social class, marriage, and personal growth.",
      "totalPages": 279,
      "rating": 4.6,
      "category": "Fiction",
      "tags": ["Romance", "Satire"],
      "publisher": "T. Egerton, Whitehall",
      "yearOfPublishing": 1813
    },
    {
      "bookID": 6,
      "bookName": "The Hobbit",
      "author": "J.R.R. Tolkien",
      "image": "src/assets/loving-book.png",
      "review": "An enchanting adventure set in Middle-earth, perfect for readers of all ages.",
      "totalPages": 310,
      "rating": 4.9,
      "category": "Fantasy",
      "tags": ["Adventure", "Quest"],
      "publisher": "George Allen & Unwin",
      "yearOfPublishing": 1937
    },
    {
      "bookID": 7,
      "bookName": "Harry Potter and the Philosopher's Stone",
      "author": "J.K. Rowling",
      "image": "src/assets/lost-book.png",
      "review": "A captivating tale of magic, friendship, and the battle between good and evil.",
      "totalPages": 332,
      "rating": 4.7,
      "category": "Fantasy",
      "tags": ["Magic", "Adventure"],
      "publisher": "Bloomsbury",
      "yearOfPublishing": 1997
    },
    {
      "bookID": 8,
      "bookName": "The Da Vinci Code",
      "author": "Dan Brown",
      "image": "src/assets/case-book.png",
      "review": "A thrilling mystery unraveling the secrets of the Catholic Church and the Holy Grail.",
      "totalPages": 454,
      "rating": 4.2,
      "category": "Mystery",
      "tags": ["Thriller", "Conspiracy"],
      "publisher": "Doubleday",
      "yearOfPublishing": 2003
    },
    {
      "bookID": 9,
      "bookName": "The Hunger Games",
      "author": "Suzanne Collins",
      "image": "src/assets/kevin-book.png",
      "review": "A gripping tale of survival and rebellion in a dystopian society where children fight to the death.",
      "totalPages": 374,
      "rating": 4.4,
      "category": "Dystopian",
      "tags": ["Young Adult", "Action"],
      "publisher": "Scholastic Corporation",
      "yearOfPublishing": 2008
    }
  ]
  export default bookList